package auth

import (
	"bufio"
	"errors"
	"net/http"
	"os"
	"strings"
	"testing"
)

// cookie builds an *http.Cookie from a name=value pair without touching a
// browser, so the pure assembler can be tested against a synthetic set.
func cookie(name, value string) *http.Cookie {
	return &http.Cookie{Name: name, Value: value}
}

// TestAssembleCookieHeader_canonical asserts the assembled header emits the known
// sign-in cookies in the fixed canonical order, then any extras alphabetically.
func TestAssembleCookieHeader_canonical(t *testing.T) {
	in := []*http.Cookie{
		cookie("SID", "sid"),
		cookie("FOO", "bar"), // extra (not in cookieOrder) => trails, alphabetical
		cookie("SIDCC", "cc"),
		cookie("LOGIN_INFO", "li"),
		cookie("__Secure-3PAPISID", "3p"),
		cookie("HSID", "hsid"),
		cookie("SAPISID", "sap"),
		cookie("AAA", "z"), // another extra
	}

	got, err := AssembleCookieHeader(in)
	if err != nil {
		t.Fatalf("AssembleCookieHeader: %v", err)
	}
	want := "HSID=hsid; SAPISID=sap; __Secure-3PAPISID=3p; SID=sid; LOGIN_INFO=li; SIDCC=cc; AAA=z; FOO=bar"
	if got != want {
		t.Errorf("header =\n  %q\nwant\n  %q", got, want)
	}
}

// TestAssembleCookieHeader_dedupAndEmpty asserts the first non-empty value wins
// for a duplicated name and that empty-valued cookies are dropped entirely.
func TestAssembleCookieHeader_dedupAndEmpty(t *testing.T) {
	in := []*http.Cookie{
		cookie("SAPISID", "first"),
		cookie("SAPISID", "second"), // duplicate => ignored
		cookie("SID", ""),           // empty => dropped
		cookie("HSID", "h"),
	}

	got, err := AssembleCookieHeader(in)
	if err != nil {
		t.Fatalf("AssembleCookieHeader: %v", err)
	}
	want := "HSID=h; SAPISID=first"
	if got != want {
		t.Errorf("header = %q, want %q", got, want)
	}
}

// TestAssembleCookieHeader_sapisidFallback asserts __Secure-3PAPISID alone (no
// plain SAPISID) is accepted as the required signing cookie.
func TestAssembleCookieHeader_sapisidFallback(t *testing.T) {
	in := []*http.Cookie{
		cookie("SID", "sid"),
		cookie("__Secure-3PAPISID", "3p"),
	}
	if _, err := AssembleCookieHeader(in); err != nil {
		t.Errorf("expected success with __Secure-3PAPISID, got %v", err)
	}
}

// TestAssembleCookieHeader_noSAPISID asserts the typed ErrNoSAPISID is returned
// (matchable with errors.Is) when no signing cookie is present.
func TestAssembleCookieHeader_noSAPISID(t *testing.T) {
	in := []*http.Cookie{
		cookie("SID", "sid"),
		cookie("HSID", "hsid"),
		cookie("YSC", "ysc"),
	}
	_, err := AssembleCookieHeader(in)
	if !errors.Is(err, ErrNoSAPISID) {
		t.Errorf("err = %v, want ErrNoSAPISID", err)
	}
}

// TestParseNetscapeCookies asserts the yt-dlp jar parser: tab-separated data
// lines become cookies, "#HttpOnly_" lines are real cookies (not comments),
// genuine comment lines and non-YouTube/Google domains are dropped, and the
// result assembles into a SAPISID-bearing header.
func TestParseNetscapeCookies(t *testing.T) {
	const jar = "# Netscape HTTP Cookie File\n" +
		"# This file is generated by yt-dlp.\n" +
		".youtube.com\tTRUE\t/\tTRUE\t1900000000\tSAPISID\tsapval\n" +
		"#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\t__Secure-3PSID\tpsidval\n" +
		".google.com\tTRUE\t/\tTRUE\t1900000000\tHSID\thsidval\n" +
		".example.com\tTRUE\t/\tFALSE\t1900000000\tTRACK\tnope\n" + // irrelevant domain => dropped
		"malformed line without tabs\n"

	got := parseNetscapeCookies(bufio.NewScanner(strings.NewReader(jar)))
	if len(got) != 3 {
		t.Fatalf("parsed %d cookies, want 3 (SAPISID, __Secure-3PSID, HSID): %+v", len(got), got)
	}
	header, err := AssembleCookieHeader(got)
	if err != nil {
		t.Fatalf("AssembleCookieHeader on parsed jar: %v", err)
	}
	for _, want := range []string{"SAPISID=sapval", "__Secure-3PSID=psidval", "HSID=hsidval"} {
		if !strings.Contains(header, want) {
			t.Errorf("assembled header %q missing %q", header, want)
		}
	}
	if strings.Contains(header, "TRACK") {
		t.Errorf("assembled header leaked a non-YouTube cookie: %q", header)
	}
}

// TestRelevantDomain covers the YouTube/Google domain filter.
func TestRelevantDomain(t *testing.T) {
	cases := map[string]bool{
		"music.youtube.com":   true,
		".youtube.com":        true,
		"youtube.com":         true,
		".google.com":         true,
		"accounts.google.com": true,
		"example.com":         false,
		"notyoutube.com":      false,
		"google.com.evil.io":  false,
		"":                    false,
	}
	for domain, want := range cases {
		if got := relevantDomain(domain); got != want {
			t.Errorf("relevantDomain(%q) = %v, want %v", domain, got, want)
		}
	}
}

// TestImportFromBrowser_unsupported asserts a bogus browser name is rejected
// without invoking yt-dlp.
func TestImportFromBrowser_unsupported(t *testing.T) {
	if _, _, err := ImportFromBrowser("netscape4"); err == nil {
		t.Error("expected error for unsupported browser, got nil")
	}
}

// TestIsBrowserRunning_unsupported asserts the running-browser detection reports
// false (never errors) for an unsupported browser id, without touching the
// process table.
func TestIsBrowserRunning_unsupported(t *testing.T) {
	if IsBrowserRunning("netscape4") {
		t.Error("IsBrowserRunning(unsupported) = true, want false")
	}
	if IsBrowserRunning("auto") {
		t.Error("IsBrowserRunning(auto) = true, want false (no single process to attribute)")
	}
}

// TestIsBrowserRunning_live exercises the real process-table check. It is skipped
// by default; set TUBEAMP_LIVE_PROC=1 (and optionally TUBEAMP_LIVE_PROC_BROWSER)
// to run it against the machine's actual processes.
func TestIsBrowserRunning_live(t *testing.T) {
	if os.Getenv("TUBEAMP_LIVE_PROC") != "1" {
		t.Skip("set TUBEAMP_LIVE_PROC=1 (and optionally TUBEAMP_LIVE_PROC_BROWSER) to run the real process check")
	}
	browser := os.Getenv("TUBEAMP_LIVE_PROC_BROWSER")
	if browser == "" {
		browser = "firefox"
	}
	t.Logf("IsBrowserRunning(%q) = %v", browser, IsBrowserRunning(browser))
}

// TestImportFromBrowser_live exercises the real yt-dlp-backed import against the
// machine's actual browser. It is skipped by default (it needs yt-dlp, a
// signed-in browser, and on macOS Keychain consent) and never logs the cookie.
func TestImportFromBrowser_live(t *testing.T) {
	if os.Getenv("TUBEAMP_LIVE_IMPORT") != "1" {
		t.Skip("set TUBEAMP_LIVE_IMPORT=1 (and optionally TUBEAMP_LIVE_IMPORT_BROWSER) to run the real browser import")
	}
	browser := os.Getenv("TUBEAMP_LIVE_IMPORT_BROWSER") // "" => auto
	header, source, err := ImportFromBrowser(browser)
	if err != nil {
		t.Fatalf("ImportFromBrowser(%q): %v", browser, err)
	}
	// Never print the header — it is a live credential. Only assert structure.
	if !strings.Contains(header, "SAPISID") {
		t.Error("imported header is missing a SAPISID cookie")
	}
	if source == "" || source == "auto" {
		t.Errorf("sourceBrowser = %q, want a concrete browser id", source)
	}
}
